spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/departments
    username: admin
    password: admin
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    properties.javax.persistence.validation.mode: none
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: departments # id приложения
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka # адрес eureka-server для регистрации сервиса

server:
  port: 8082 # порт будет определяться eureka-server

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n' # формат логов


