spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/departments
    username: admin
    password: admin
  liquibase:
    change-log: classpath:db/changelog/changelog-master-departments.yaml
    enabled: true
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  application:
    name: departments
  devtools:
    restart:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8082

logging:
  pattern:
    console: '%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n'

feign:
  circuitbreaker:
    enabled: true
